name: Deploy to VM Broo

on:
  push:
    branches:
      - master

jobs:

  build-and-upload-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: indrafajar/spring-spring-index-be:latest
        env:
          DATABASE_ENV: ${{ secrets.ENV_FILE }}
  deploy-on-vm1:
    runs-on: ubuntu-latest
    needs: build-and-upload-to-docker-hub
    steps:
    
      - name: Deploy to second VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
          HOST: ${{ secrets.VM_HOST }}  # Update with your VM IP
          USER: ${{ secrets.VM_USERNAME }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/vm_key
          chmod 600 /tmp/vm_key

          ssh -o StrictHostKeyChecking=no -i /tmp/vm_key $USER@$HOST << 'EOF'
            docker pull docker.io/indrafajar/spring-index-be:latest
            docker stop spring-index-be || true
            docker rm spring-index-be || true
            docker run -d --name spring-index-be --restart always --network pos-app -p 3100:3000 docker.io/indrafajar/spring-index-be:latest
            docker image prune -f
          EOF
  deploy-on-vm2:
    needs: build-and-upload-to-docker-hub
    runs-on: ubuntu-latest
    steps:
    
      - name: Deploy to second VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
          HOST: ${{ secrets.VM_HOST2 }}  # Update with your VM IP
          USER: ${{ secrets.VM_USERNAME }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/vm_key
          chmod 600 /tmp/vm_key

          ssh -o StrictHostKeyChecking=no -i /tmp/vm_key $USER@$HOST << 'EOF'
            docker pull indrafajar/spring-index-be:latest
            docker stop spring-index-be || true
            docker rm spring-index-be || true
            docker run -d --name spring-index-be --env-file ~/spring-index-be/.env --restart unless-stopped --network pos-app -p 3100:3000 indrafajar/spring-index-be:latest
            docker image prune -f
          EOF

