name: Deploy to VM Broo

on:
  push:
    branches:
      - master

jobs:

  deploy-on-vm:
    runs-on: ubuntu-latest
    # needs: build-docker-image    
    steps:
    
      - name: Deploy to second VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
          HOST: ${{ secrets.VM_HOST }}  # Update with your VM IP
          USER: ${{ secrets.VM_USERNAME }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/vm_key
          chmod 600 /tmp/vm_key

          ssh -o StrictHostKeyChecking=no -i /tmp/vm_key $USER@$HOST << 'EOF'
            sh deploy.sh
          EOF

