name: Deploy to VM Broo

on:
  push:
    branches:
      - master  # Adjust this to your deployment branch

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: indrafajar/spring-index-be:latest  # Update this

  deploy-on-vm:
    runs-on: ubuntu-latest
    needs: build-docker-image    
    steps:
    
      - name: Deploy to second VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
          HOST: ${{ secrets.VM_HOST }}  # Update with your VM IP
          USER: ${{ secrets.VM_USERNAME }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/vm_key
          chmod 600 /tmp/vm_key

          ssh -o StrictHostKeyChecking=no -i /tmp/vm_key $USER@$HOST << 'EOF'
            sh deploy.sh
          EOF

